1er cours https://docs.pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html sur les TENSORS

In [ ]:
import torch
import numpy as np

TENSOR INITIALIZATION

In [3]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [5]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(np_array,"\n", x_np)

[[1 2]
 [3 4]] 
 tensor([[1, 2],
        [3, 4]])


In [ ]:
x_ones = torch.ones_like(x_data)
print(x_ones)
x_rand = torch.rand_like(x_data, dtype=torch.float) #la ligne dtype est obligatoire, et le type doit etre un float
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.8316, 0.1081],
        [0.1461, 0.7712]])
tensor([[0.0498, 0.6549],
        [0.5091, 0.7605]])


In [15]:
shape=(1,2)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zero_tensor = torch.zeros(shape)
print(rand_tensor,ones_tensor,zero_tensor)

tensor([[0.9680, 0.3985]]) tensor([[1., 1.]]) tensor([[0., 0.]])


TENSORS ATTRIBUTES

In [14]:
tensor = torch.rand(2,3)
print(tensor.shape)
print(tensor.dtype)
print(tensor.device)


torch.Size([2, 3])
torch.float32
cpu


TENSORS OPERATIONS

In [16]:
# We move our tensor to the GPU if available
device = torch.accelerator.current_accelerator().type if torch.accelerator.is_available() else 'cpu'
tensor = tensor.to(device)
print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cpu


In [18]:
tensor = torch.ones(4,4)
tensor[:,2] = 0
print(tensor)

tensor([[1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [1., 1., 0., 1.]])


In [24]:
t1 = torch.cat([tensor,tensor,tensor], dim=1)
print(t1)

tensor([[1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1.],
        [1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1.],
        [1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1.],
        [1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1.]])


In [ ]:
tensor = torch.ones(3,2)
tensor[:,1] = 0
tensor *= 2
print(tensor) 
print(tensor.mul(tensor)) #mets au carrés chaque coeff du tenseur
print(tensor*tensor) #meme opération, différente syntax

tensor([[2., 0.],
        [2., 0.],
        [2., 0.]])
tensor([[4., 0.],
        [4., 0.],
        [4., 0.]])
tensor([[4., 0.],
        [4., 0.],
        [4., 0.]])


In [ ]:
tensor = torch.ones(4,4)
tensor[:,1] = 0
print(tensor.matmul(tensor.T)) #multiplie 2 tensor, tensor.T doit etre la transposée
print(tensor@tensor.T) #autre syntax

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


In [ ]:
tensor = torch.rand(2,3)
print(tensor)
tensor.add_(5) #ajoute 5 à chaque coeff
print(tensor)

tensor([[0.6761, 0.1132, 0.4523],
        [0.4589, 0.4409, 0.5118]])
tensor([[5.6761, 5.1132, 5.4523],
        [5.4589, 5.4409, 5.5118]])


BRIDGE WITH NUMPY

In [37]:
t = torch.ones(5)
print(t)
n = t.numpy()
print(n)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [40]:
t.add_(1)
print(t,n) #prouve la dépendance de t et n

tensor([3., 3., 3., 3., 3.]) [3. 3. 3. 3. 3.]


In [ ]:
#Meme chose dans l'autre sens
n = np.ones(5)
print(n)
t = torch.from_numpy(n)
print(t)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [42]:
np.add(n,1,out=n)
print(t,n)

tensor([2., 2., 2., 2., 2.], dtype=torch.float64) [2. 2. 2. 2. 2.]
